version: '3'

services:
  nginx: 
    networks:
      - predict_app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443

networks:
  predict_app:
    external: true