version: '3'

services:
  nginx: 
    networks:
      - predict_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80

networks:
  predict_app:
